In [2]:
import torch

# GPU 사용 가능 여부
print("CUDA available:", torch.cuda.is_available())

print("Number of GPUs:", torch.cuda.device_count())

if torch.cuda.is_available():
    print("Current GPU:", torch.cuda.get_device_name(torch.cuda.current_device()))

device = "cuda"

a = torch.randn(3, 3, device=device)
b = torch.randn(3, 3, device=device)
c = torch.matmul(a, b)

print("\n✅ a =\n", a)
print("\n✅ b =\n", b)
print("\n✅ a @ b =\n", c)

CUDA available: True
Number of GPUs: 1
Current GPU: NVIDIA GeForce RTX 3050 Laptop GPU

✅ a =
 tensor([[-2.6540,  0.7616,  0.1934],
        [ 0.2190, -1.2721, -0.2372],
        [ 0.2334,  0.1768, -1.2738]], device='cuda:0')

✅ b =
 tensor([[-0.1665, -0.8465, -0.9867],
        [ 0.5051, -0.8505, -0.3782],
        [-0.8669, -1.1263, -0.6953]], device='cuda:0')

✅ a @ b =
 tensor([[ 0.6588,  1.3811,  2.1961],
        [-0.4734,  1.1636,  0.4300],
        [ 1.1546,  1.0868,  0.5885]], device='cuda:0')
